server:
  port: 8024 
  
spring:
  datasource:    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.2:3306/untactTeacher?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: sbsst
    password: sbs123414  
mybatis:  type-aliases-package: com.example.demo.dto